import type { PublicContentLanguage } from 'shared-types';

export interface TouristMessages {
  readonly chooseLanguage: string; readonly mapMenu: string; readonly all: string; readonly poweredBy: string;
  readonly searchPlaces: string; readonly closeSearch: string; readonly searchPlaceholder: string; readonly searchHint: string; readonly noPlacesFound: string;
  readonly closePlaceDetails: string; readonly closePage: string; readonly previousPhoto: string; readonly nextPhoto: string;
  readonly serviceOptions: string; readonly dineIn: string; readonly takeaway: string; readonly delivery: string;
  readonly openNow: string; readonly closed: string; readonly hideHours: string; readonly seeHours: string; readonly free: string;
  readonly liveCamera: string; readonly closeCameraDetails: string; readonly streamNotConfigured: string; readonly playLive: string; readonly connecting: string; readonly stop: string;
  readonly live: string; readonly openDetails: string; readonly closeCameraPreview: string; readonly map: string; readonly showingLocation: string;
  readonly mapUnavailable: string; readonly mapboxTokenMissing: string; readonly loadingMap: string; readonly noPublishedPlaces: string; readonly noCategoryPlaces: string; readonly mapOf: string;
  readonly mapLoadError: string; readonly readMore: string; readonly readLess: string; readonly photoBy: string; readonly myLocationMarker: string;
  readonly locationErrors: { readonly unsupported: string; readonly denied: string; readonly unavailable: string; readonly failed: string };
}

const EN: TouristMessages = { chooseLanguage:'Choose language', mapMenu:'Map menu', all:'All', poweredBy:'Powered by Tourist Map System', searchPlaces:'Search places', closeSearch:'Close search', searchPlaceholder:'Search places…', searchHint:'Start typing to find a place.', noPlacesFound:'No places found.', closePlaceDetails:'Close place details', closePage:'Close page', previousPhoto:'Previous photo', nextPhoto:'Next photo', serviceOptions:'Service options', dineIn:'Dine-in', takeaway:'Takeaway', delivery:'Delivery', openNow:'Open now', closed:'Closed', hideHours:'Hide hours', seeHours:'See hours', free:'Free', liveCamera:'Live Camera', closeCameraDetails:'Close camera details', streamNotConfigured:'Live stream is not configured.', playLive:'Play Live', connecting:'Connecting…', stop:'Stop', live:'LIVE', openDetails:'Open details', closeCameraPreview:'Close camera preview', map:'Map', showingLocation:'Showing your current location.', mapUnavailable:'Map preview is unavailable in this environment.', mapboxTokenMissing:'Mapbox map requires NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN to be configured.', loadingMap:'Loading map…', noPublishedPlaces:'No places have been published yet.', noCategoryPlaces:'No places in this category yet.', mapOf:'Map of', mapLoadError:"We couldn't load this map right now.", readMore:'Read more', readLess:'Read less', photoBy:'Photo by', myLocationMarker:'Your location', locationErrors:{unsupported:"Location isn't supported in this browser.", denied:'Location access was denied.', unavailable:'Location is unavailable.', failed:'Location request failed.'} };
const MESSAGES: Record<PublicContentLanguage, TouristMessages> = {
  en: EN,
  ja: { ...EN, chooseLanguage:'言語を選択', mapMenu:'地図メニュー', all:'すべて', poweredBy:'Tourist Map System 提供', searchPlaces:'場所を検索', closeSearch:'検索を閉じる', searchPlaceholder:'場所を検索…', searchHint:'入力して場所を検索してください。', noPlacesFound:'場所が見つかりません。', closePlaceDetails:'場所の詳細を閉じる', closePage:'ページを閉じる', previousPhoto:'前の写真', nextPhoto:'次の写真', serviceOptions:'サービス', dineIn:'店内飲食', takeaway:'テイクアウト', delivery:'デリバリー', openNow:'営業中', closed:'休業中', hideHours:'営業時間を隠す', seeHours:'営業時間を見る', free:'無料', liveCamera:'ライブカメラ', closeCameraDetails:'カメラの詳細を閉じる', streamNotConfigured:'ライブ配信は設定されていません。', playLive:'ライブ再生', connecting:'接続中…', stop:'停止', live:'ライブ', openDetails:'詳細を開く', closeCameraPreview:'カメラプレビューを閉じる', map:'地図', showingLocation:'現在地を表示しています。', locationErrors:{unsupported:'このブラウザでは位置情報を利用できません。', denied:'位置情報へのアクセスが拒否されました。', unavailable:'位置情報を取得できません。', failed:'位置情報の取得に失敗しました。'} },
  'zh-CN': { ...EN, chooseLanguage:'选择语言', mapMenu:'地图菜单', all:'全部', poweredBy:'由 Tourist Map System 提供', searchPlaces:'搜索地点', closeSearch:'关闭搜索', searchPlaceholder:'搜索地点…', searchHint:'开始输入以查找地点。', noPlacesFound:'未找到地点。', closePlaceDetails:'关闭地点详情', closePage:'关闭页面', previousPhoto:'上一张照片', nextPhoto:'下一张照片', serviceOptions:'服务选项', dineIn:'堂食', takeaway:'外带', delivery:'配送', openNow:'营业中', closed:'已关闭', hideHours:'隐藏营业时间', seeHours:'查看营业时间', free:'免费', liveCamera:'直播摄像头', closeCameraDetails:'关闭摄像头详情', streamNotConfigured:'尚未配置直播。', playLive:'播放直播', connecting:'连接中…', stop:'停止', live:'直播', openDetails:'打开详情', closeCameraPreview:'关闭摄像头预览', map:'地图', showingLocation:'正在显示您的当前位置。', locationErrors:{unsupported:'此浏览器不支持位置服务。', denied:'位置访问被拒绝。', unavailable:'无法获取位置。', failed:'位置请求失败。'} },
  'zh-TW': { ...EN, chooseLanguage:'選擇語言', mapMenu:'地圖選單', all:'全部', poweredBy:'由 Tourist Map System 提供', searchPlaces:'搜尋地點', closeSearch:'關閉搜尋', searchPlaceholder:'搜尋地點…', searchHint:'開始輸入以尋找地點。', noPlacesFound:'找不到地點。', closePlaceDetails:'關閉地點詳細資料', closePage:'關閉頁面', previousPhoto:'上一張照片', nextPhoto:'下一張照片', serviceOptions:'服務選項', dineIn:'內用', takeaway:'外帶', delivery:'外送', openNow:'營業中', closed:'已關閉', hideHours:'隱藏營業時間', seeHours:'查看營業時間', free:'免費', liveCamera:'直播攝影機', closeCameraDetails:'關閉攝影機詳細資料', streamNotConfigured:'尚未設定直播。', playLive:'播放直播', connecting:'連線中…', stop:'停止', live:'直播', openDetails:'開啟詳細資料', closeCameraPreview:'關閉攝影機預覽', map:'地圖', showingLocation:'正在顯示您的目前位置。', locationErrors:{unsupported:'此瀏覽器不支援位置服務。', denied:'位置存取遭拒。', unavailable:'無法取得位置。', failed:'位置要求失敗。'} },
  ko: { ...EN, chooseLanguage:'언어 선택', mapMenu:'지도 메뉴', all:'전체', poweredBy:'Tourist Map System 제공', searchPlaces:'장소 검색', closeSearch:'검색 닫기', searchPlaceholder:'장소 검색…', searchHint:'장소를 찾으려면 입력하세요.', noPlacesFound:'장소를 찾을 수 없습니다.', closePlaceDetails:'장소 상세 닫기', closePage:'페이지 닫기', previousPhoto:'이전 사진', nextPhoto:'다음 사진', serviceOptions:'서비스 옵션', dineIn:'매장 식사', takeaway:'포장', delivery:'배달', openNow:'영업 중', closed:'영업 종료', hideHours:'영업시간 숨기기', seeHours:'영업시간 보기', free:'무료', liveCamera:'라이브 카메라', closeCameraDetails:'카메라 상세 닫기', streamNotConfigured:'라이브 스트림이 설정되지 않았습니다.', playLive:'라이브 재생', connecting:'연결 중…', stop:'중지', live:'라이브', openDetails:'상세 보기', closeCameraPreview:'카메라 미리보기 닫기', map:'지도', showingLocation:'현재 위치를 표시하고 있습니다.', locationErrors:{unsupported:'이 브라우저는 위치 정보를 지원하지 않습니다.', denied:'위치 접근이 거부되었습니다.', unavailable:'위치를 사용할 수 없습니다.', failed:'위치 요청에 실패했습니다.'} },
  fr: { ...EN, chooseLanguage:'Choisir la langue', mapMenu:'Menu de la carte', all:'Tout', poweredBy:'Propulsé par Tourist Map System', searchPlaces:'Rechercher des lieux', closeSearch:'Fermer la recherche', searchPlaceholder:'Rechercher un lieu…', searchHint:'Commencez à saisir pour trouver un lieu.', noPlacesFound:'Aucun lieu trouvé.', closePlaceDetails:'Fermer les détails du lieu', closePage:'Fermer la page', previousPhoto:'Photo précédente', nextPhoto:'Photo suivante', serviceOptions:'Services', dineIn:'Sur place', takeaway:'À emporter', delivery:'Livraison', openNow:'Ouvert', closed:'Fermé', hideHours:'Masquer les horaires', seeHours:'Voir les horaires', free:'Gratuit', liveCamera:'Caméra en direct', closeCameraDetails:'Fermer les détails de la caméra', streamNotConfigured:'Le flux en direct n’est pas configuré.', playLive:'Lire en direct', connecting:'Connexion…', stop:'Arrêter', live:'EN DIRECT', openDetails:'Ouvrir les détails', closeCameraPreview:'Fermer l’aperçu de la caméra', map:'Carte', showingLocation:'Votre position est affichée.', locationErrors:{unsupported:'La géolocalisation n’est pas prise en charge par ce navigateur.', denied:'Accès à la position refusé.', unavailable:'Position indisponible.', failed:'Échec de la demande de position.'} },
  es: { ...EN, chooseLanguage:'Elegir idioma', mapMenu:'Menú del mapa', all:'Todo', poweredBy:'Con tecnología de Tourist Map System', searchPlaces:'Buscar lugares', closeSearch:'Cerrar búsqueda', searchPlaceholder:'Buscar un lugar…', searchHint:'Empieza a escribir para encontrar un lugar.', noPlacesFound:'No se encontraron lugares.', closePlaceDetails:'Cerrar detalles del lugar', closePage:'Cerrar página', previousPhoto:'Foto anterior', nextPhoto:'Foto siguiente', serviceOptions:'Servicios', dineIn:'Comer allí', takeaway:'Para llevar', delivery:'Entrega', openNow:'Abierto ahora', closed:'Cerrado', hideHours:'Ocultar horarios', seeHours:'Ver horarios', free:'Gratis', liveCamera:'Cámara en directo', closeCameraDetails:'Cerrar detalles de la cámara', streamNotConfigured:'La transmisión en directo no está configurada.', playLive:'Reproducir en directo', connecting:'Conectando…', stop:'Detener', live:'EN DIRECTO', openDetails:'Abrir detalles', closeCameraPreview:'Cerrar vista previa de la cámara', map:'Mapa', showingLocation:'Mostrando tu ubicación actual.', locationErrors:{unsupported:'Este navegador no admite la ubicación.', denied:'Se denegó el acceso a la ubicación.', unavailable:'La ubicación no está disponible.', failed:'No se pudo obtener la ubicación.'} },
};

const EXTRA_MESSAGES: Partial<Record<PublicContentLanguage, Pick<TouristMessages, 'mapLoadError' | 'readMore' | 'readLess' | 'photoBy' | 'myLocationMarker'>>> = {
  ja: { mapLoadError:'地図を読み込めませんでした。', readMore:'続きを読む', readLess:'折りたたむ', photoBy:'撮影者：', myLocationMarker:'現在地' },
  'zh-CN': { mapLoadError:'无法加载地图。', readMore:'阅读更多', readLess:'收起', photoBy:'照片来源：', myLocationMarker:'当前位置' },
  'zh-TW': { mapLoadError:'無法載入地圖。', readMore:'閱讀更多', readLess:'收起', photoBy:'照片來源：', myLocationMarker:'目前位置' },
  ko: { mapLoadError:'지도를 불러오지 못했습니다.', readMore:'더 보기', readLess:'접기', photoBy:'사진 제공:', myLocationMarker:'현재 위치' },
  fr: { mapLoadError:'Impossible de charger la carte.', readMore:'Lire la suite', readLess:'Réduire', photoBy:'Photo par', myLocationMarker:'Votre position' },
  es: { mapLoadError:'No se pudo cargar el mapa.', readMore:'Leer más', readLess:'Mostrar menos', photoBy:'Foto de', myLocationMarker:'Tu ubicación' },
};

export function resolveTouristMessages(selected: PublicContentLanguage, defaultLanguage: PublicContentLanguage): TouristMessages {
  const base = MESSAGES[selected] ?? MESSAGES[defaultLanguage] ?? EN;
  return { ...base, ...(EXTRA_MESSAGES[selected] ?? EXTRA_MESSAGES[defaultLanguage] ?? {}) };
}

export { MESSAGES as TOURIST_MESSAGES };
